version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - app
  db:
    image: postgres:10
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - ./static:/static
    expose:
      - 8000
    depends_on:
      - db