# Generated by Django 2.2.5 on 2019-10-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='section_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video_description',
            field=models.TextField(default=''),
        ),
    ]
