# Generated by Django 2.2.5 on 2019-10-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20191005_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
