# Generated by Django 2.2.5 on 2019-10-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20191012_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
