# Generated by Django 2.2.5 on 2019-10-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20191012_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_duration_in_minutes',
            new_name='video_duration_in_seconds',
        ),
    ]
